apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2
  selector: 
    matchlables:
      app :flask
  template:
    metadata:
      template:
        app: flask
    spec:
    containers:
      - name: flask-app
        image: flask-app:latest
        ports:
          - containerPort: 5000
  